version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/index.html:/etc/nginx/html/index.html
    restart: always
  database:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: 1111
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  gogs:
    image: gogs/gogs:latest
    restart: always
    ports:
      - "10022:22"
      - "3000:3000"
    links:
      - database
    environment:
      - RUN_CROND=true
    volumes:
      - ./gogs-data:/data
    depends_on:
      - database
  jenkins:
    image: siriuszg/jenkins-with-docker:latest
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Shanghai
